services:
  - type: web
    name: blogify
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 80
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    # Explicitly clear any dashboard overrides
    startCommand: entrypoint.sh
    # Run migrations before starting the new version
    releaseCommand: php migrate.php && php seed_categories.php
