# Log all queries
log-queries
# Don't use /etc/hosts as it might conflict
no-hosts
# Map all *.blogify.dev and blogify.dev to locally bound IP (127.0.0.1)
address=/blogify.dev/127.0.0.1
# Use Google DNS as fallback
server=8.8.8.8
server=8.8.4.4
